version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - store_test_results:
          path: ./test-results/
      - checkout
      - run:
          working_directory: ./
          name: Run tests
          command: |
            dotnet test

  pack:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    parallelism: 1 # figure out later if needed.
    steps:
      - checkout
      - run:
          working_directory: ./
          name: Run dotnet pack
          command: |
            dotnet pack --configuration Release
      - store_artifacts:
          path: ./src/Overmock/bin/Release/
          destination: ./pack
workflows:
  build-test-and-pack:
    jobs:
      - build-and-test
      - pack
