version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - store_test_results:
          path: ./bin/
      - checkout
      - run:
          working_directory: ./src/Overmock.Examples.Tests/
          name: Run tests
          command: |
            dotnet test

  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    parallelism: 3
    steps:
      - checkout
      - run:
          working_directory: ./src/Overmock/
          name: Run build
          command: |
            dotnet build
      - store_artifacts:
          path: ./bin/
          destination: ./artifacts
workflows:
  sample:
    jobs:
      - build-and-test
